let express=require("express")
let router=express.Router()
let userController=require("../controller/user.controller")

router.post("/signUp",userController.storeUserDetails)
router.get("/signin",userController.getUserDetails)
router.post("/raiseTicket",userController.raiseTicket)
router.get("/getraiseTicket",userController.getRaiseTickets)
router.put("/editUserProfile",userController.editUserProfile)
router.post("/addToCart",userController.addToCart)
router.delete("/deleteFromCart/:pname",userController.deleteFromCart)
router.get("/viewCartItems",userController.getCartItems)
router.put("/editFunds",userController.editFunds)
router.post("/addFunds",userController.addFunds)
router.get("/getFunds",userController.getFunds)
router.put("/updateIncorrectCount",userController.updateIncorrectCount)
router.put("/updateIncorrectlock",userController.updateIncorrectLock)
router.delete("/deleteTicket/:email",userController.deleteTicket)
router.put("/unlockUser",userController.unlockUser)
router.put("/updateCartItems",userController.updateCartItems)
router.put("/updateCartItemsCancel",userController.updateCartItemsCancel)
router.get("/viewCartItemsReport",userController.viewCartItemsReport)

module.exports=router